# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addlistUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import test


class AddListUI_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 600))
        self.label.setStyleSheet("background-color: rgba(0, 90, 145, 200);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(255, 255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gobackButton = QtWidgets.QPushButton(Dialog)
        self.gobackButton.setGeometry(QtCore.QRect(20, 20, 30, 30))
        self.gobackButton.setStyleSheet(
            "background-color: rgba(0, 90, 145, 0);")
        self.gobackButton.setText("")
        self.gobackButton.setObjectName("gobackButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(160, 80, 80, 80))
        self.label_4.setStyleSheet("border: 2px;\n"
                                   "border-radius: 40px;\n"
                                   "background-color: rgb(85, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 200, 340, 40))
        self.comboBox.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
                                    "border:none;\n"
                                    "border-bottom: 1px solid rgba(255, 255, 255, 200);\n"
                                    "color: rgba(255, 255, 255, 255);\n"
                                    "padding-bottom:7px;")
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 270, 340, 40))
        self.lineEdit.setStyleSheet("background-color: rgba(0, 90, 145, 0);\n"
                                    "border:none;\n"
                                    "border-bottom: 1px solid rgba(255, 255, 255, 80);\n"
                                    "color: rgba(255, 255, 255, 240);\n"
                                    "padding-bottom:7px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 340, 340, 40))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 90, 145, 0);\n"
                                      "border:none;\n"
                                      "border-bottom: 1px solid rgba(255, 255, 255, 80);\n"
                                      "color: rgba(255, 255, 255, 240);\n"
                                      "padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 410, 340, 40))
        self.lineEdit_3.setStyleSheet("background-color: rgba(0, 90, 145, 0);\n"
                                      "border:none;\n"
                                      "border-bottom: 1px solid rgba(255, 255, 255, 80);\n"
                                      "color: rgba(255, 255, 255, 240);\n"
                                      "padding-bottom:7px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.completeadditemButton = QtWidgets.QPushButton(Dialog)
        self.completeadditemButton.setGeometry(QtCore.QRect(30, 500, 340, 40))
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.completeadditemButton.setFont(font)
        self.completeadditemButton.setStyleSheet("background-color: rgb(0, 180, 220);\n"
                                                 "color: rgba(255, 255, 255, 255);")
        self.completeadditemButton.setObjectName("completeadditemButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Add new thing"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Work"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Time"))
        self.lineEdit_3.setPlaceholderText(
            _translate("Dialog", "Notification"))
        self.completeadditemButton.setText(
            _translate("Dialog", "ADD YOUR THING"))
