# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolistUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import test


class TodolistUI_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 600))
        self.label.setStyleSheet("background-color: rgb(166, 184, 196)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 80, 600))
        self.label_2.setStyleSheet("background-color: rgb(233, 237, 241);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.imageLabel = QtWidgets.QLabel(Dialog)
        self.imageLabel.setGeometry(QtCore.QRect(0, 0, 80, 80))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.additemButton = QtWidgets.QPushButton(Dialog)
        self.additemButton.setGeometry(QtCore.QRect(0, 80, 80, 80))
        self.additemButton.setStyleSheet("border-image: url(:/newPrefix/plusicon.png);\n"
                                         "")
        self.additemButton.setText("")
        self.additemButton.setObjectName("additemButton")
        self.deleteitemButton = QtWidgets.QPushButton(Dialog)
        self.deleteitemButton.setGeometry(QtCore.QRect(0, 160, 80, 80))
        self.deleteitemButton.setStyleSheet(
            "border-image: url(:/newPrefix/minusicon.png);")
        self.deleteitemButton.setText("")
        self.deleteitemButton.setObjectName("deleteitemButton")
        self.turnoffButton = QtWidgets.QPushButton(Dialog)
        self.turnoffButton.setGeometry(QtCore.QRect(0, 520, 80, 80))
        self.turnoffButton.setStyleSheet("border-image: url(:/newPrefix/power.png);\n"
                                         "")
        self.turnoffButton.setText("")
        self.turnoffButton.setObjectName("turnoffButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.todoListWidget = QtWidgets.QListWidget(Dialog)
        self.todoListWidget.setGeometry(QtCore.QRect(90, 80, 301, 211))
        self.todoListWidget.setStyleSheet(
            "background-color: rgb(233, 237, 241);")
        self.todoListWidget.setObjectName("todoListWidget")
        self.inprogressListWidget = QtWidgets.QListWidget(Dialog)
        self.inprogressListWidget.setGeometry(QtCore.QRect(90, 380, 301, 211))
        self.inprogressListWidget.setStyleSheet(
            "background-color: rgb(233, 237, 241);")
        self.inprogressListWidget.setObjectName("inprogressListWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.todoListWidget, self.inprogressListWidget)
        Dialog.setTabOrder(self.inprogressListWidget, self.additemButton)
        Dialog.setTabOrder(self.additemButton, self.deleteitemButton)
        Dialog.setTabOrder(self.deleteitemButton, self.turnoffButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "TO DO"))
        self.label_4.setText(_translate("Dialog", "IN PROGRESS"))
